name: Greet Everyone
# Work flow is triggered on pushes to directory
on: [push]


jobs:
  build:
    # Job name is the greeting
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
        id: Hello
      # This step prints the output (time) from the previous step
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}'
